////////////////////////////////////////////////////////////////////////
// Generated by bounded/enumeration
////////////////////////////////////////////////////////////////////////

package model

import (
	"encoding/json"
	"fmt"
	"strings"
)

type InputSourceEnum string

const (
	InputSource_Json    InputSourceEnum = "json"
	InputSource_Unknown InputSourceEnum = "unknown"
	InputSource_Yaml    InputSourceEnum = "yaml"
)

var (
	InputSourceEnums = []InputSourceEnum{
		InputSource_Json,
		InputSource_Unknown,
		InputSource_Yaml,
	}
)

func IsInputSourceEnum(v string) bool {
	var f bool

	for _, e := range InputSourceEnums {
		if string(e) == v {
			f = true
			break
		}
	}

	return f
}

func InputSourceEnumParse(v string) (InputSourceEnum, error) {
	var o InputSourceEnum
	var f bool
	n := strings.ToLower(v)

	for _, e := range InputSourceEnums {
		if strings.ToLower(e.String()) == n {
			o = e
			f = true
			break
		}
	}

	if !f {
		return o, ErrInputSourceEnumNotFound(v)
	}

	return o, nil
}

func ErrInputSourceEnumNotFound(v string) error {
	var ss []string

	for _, e := range InputSourceEnums {
		ss = append(ss, string(e))
	}

	return fmt.Errorf(
		"invalid enumeration type '%v', must be one of %v",
		v, strings.Join(ss, ","),
	)
}

func (t InputSourceEnum) String() string {
	return string(t)
}

func (t InputSourceEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal([]byte(t))
}

func (t *InputSourceEnum) UnmarshalJSON(data []byte) error {
	var s string

	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	e, err := InputSourceEnumParse(s)

	if err != nil {
		return err
	}

	t = &e

	return nil
}
