////////////////////////////////////////////////////////////////////////
// Generated by bounded/enumeration
////////////////////////////////////////////////////////////////////////

package model

import (
	"encoding/json"
	"fmt"
	"strings"
)

type TemplateTypeEnum string

const (
	TemplateType_Model     TemplateTypeEnum = "model"
	TemplateType_Namespace TemplateTypeEnum = "namespace"
	TemplateType_Operation TemplateTypeEnum = "operation"
)

var (
	TemplateTypeEnums = []TemplateTypeEnum{
		TemplateType_Model,
		TemplateType_Namespace,
		TemplateType_Operation,
	}
)

func IsTemplateTypeEnum(v string) bool {
	var f bool

	for _, e := range TemplateTypeEnums {
		if string(e) == v {
			f = true
			break
		}
	}

	return f
}

func TemplateTypeEnumParse(v string) (TemplateTypeEnum, error) {
	var o TemplateTypeEnum
	var f bool
	n := strings.ToLower(v)

	for _, e := range TemplateTypeEnums {
		if strings.ToLower(e.String()) == n {
			o = e
			f = true
			break
		}
	}

	if !f {
		return o, ErrTemplateTypeEnumNotFound(v)
	}

	return o, nil
}

func ErrTemplateTypeEnumNotFound(v string) error {
	var ss []string

	for _, e := range TemplateTypeEnums {
		ss = append(ss, string(e))
	}

	return fmt.Errorf(
		"invalid enumeration type '%v', must be one of %v",
		v, strings.Join(ss, ","),
	)
}

func (t TemplateTypeEnum) String() string {
	return string(t)
}

func (t TemplateTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

func (t *TemplateTypeEnum) UnmarshalJSON(data []byte) error {
	var s string

	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	e, err := TemplateTypeEnumParse(s)

	if err != nil {
		return err
	}

	t = &e

	return nil
}
