module: boundedinfinity/test/gomux
version: '1.16'
outDir: /tmp/generator/go/server/echo/handlebars
requires:
  - package: gopkg.in/yaml.v2
    version: v2.4.0
  - package: github.com/labstack/echo/v4
    version: v4.2.1
  - package: gopkg.in/go-playground/validator.v9
    version: v9.31.0
global:
  - template: ./go-mod.handlebars
    output: go.mod
  - template: main.go.handlebars
    output: main.go
    package: main
schemas:
  - package: boundedinfinity/gomux/model
    template: model.handlebars
    output: model/model.gen.go
  - package: boundedinfinity/gomux/web
    template: web.handlebars
    output: web/main.gen.go