//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Any change will be overwritten                                                   *
//* Generated by github.com/boundedinfinity/enumer                                   *
//*                                                                                  *
//************************************************************************************

package fileext

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

type FileExt string
type FileExts []FileExt

func Slice(es ...FileExt) FileExts {
	var s FileExts

	for _, e := range es {
		s = append(s, e)
	}

	return s
}

const (
	Json FileExt = "json"
	Yaml FileExt = "yaml"
	Yml  FileExt = "yml"
)

var (
	All = FileExts{
		Json,
		Yaml,
		Yml,
	}
)

func Is(v string) bool {
	return All.Is(v)
}

func Parse(v string) (FileExt, error) {
	return All.Parse(v)
}

func Strings() []string {
	return All.Strings()
}

func (t FileExt) String() string {
	return string(t)
}

var ErrFileExtInvalid = errors.New("invalid enumeration type")

func Error(vs FileExts, v string) error {
	return fmt.Errorf(
		"%w '%v', must be one of %v",
		ErrFileExtInvalid, v, strings.Join(vs.Strings(), ","),
	)
}

func (t FileExts) Strings() []string {
	var ss []string

	for _, v := range t {
		ss = append(ss, v.String())
	}

	return ss
}

func (t FileExts) Parse(v string) (FileExt, error) {
	var o FileExt
	var f bool
	n := strings.ToLower(v)

	for _, e := range t {
		if strings.ToLower(e.String()) == n {
			o = e
			f = true
			break
		}
	}

	if !f {
		return o, Error(t, v)
	}

	return o, nil
}

func (t FileExts) Is(v string) bool {
	var f bool

	for _, e := range t {
		if string(e) == v {
			f = true
			break
		}
	}

	return f
}

func (t FileExts) Contains(v FileExt) bool {
	for _, e := range t {
		if e == v {
			return true
		}
	}

	return false
}

func (t FileExt) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

func (t *FileExt) UnmarshalJSON(data []byte) error {
	var s string

	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	e, err := Parse(s)

	if err != nil {
		return err
	}

	*t = e

	return nil
}
