//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Any change will be overwritten                                                   *
//* Generated by github.com/boundedinfinity/enumer                                   *
//*                                                                                  *
//************************************************************************************

package template_ext

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

type TemplateExt string
type TemplateExts []TemplateExt

func Slice(es ...TemplateExt) TemplateExts {
	var s TemplateExts

	for _, e := range es {
		s = append(s, e)
	}

	return s
}

const (
	Gotmpl     TemplateExt = "gotmpl"
	Handlebars TemplateExt = "handlebars"
)

var (
	All = TemplateExts{
		Gotmpl,
		Handlebars,
	}
)

func Is(v string) bool {
	return All.Is(v)
}

func Parse(v string) (TemplateExt, error) {
	return All.Parse(v)
}

func Strings() []string {
	return All.Strings()
}

func (t TemplateExt) String() string {
	return string(t)
}

var ErrTemplateExtInvalid = errors.New("invalid enumeration type")

func Error(vs TemplateExts, v string) error {
	return fmt.Errorf(
		"%w '%v', must be one of %v",
		ErrTemplateExtInvalid, v, strings.Join(vs.Strings(), ","),
	)
}

func (t TemplateExts) Strings() []string {
	var ss []string

	for _, v := range t {
		ss = append(ss, v.String())
	}

	return ss
}

func (t TemplateExts) Parse(v string) (TemplateExt, error) {
	var o TemplateExt
	var f bool
	n := strings.ToLower(v)

	for _, e := range t {
		if strings.ToLower(e.String()) == n {
			o = e
			f = true
			break
		}
	}

	if !f {
		return o, Error(t, v)
	}

	return o, nil
}

func (t TemplateExts) Is(v string) bool {
	var f bool

	for _, e := range t {
		if string(e) == v {
			f = true
			break
		}
	}

	return f
}

func (t TemplateExts) Contains(v TemplateExt) bool {
	for _, e := range t {
		if e == v {
			return true
		}
	}

	return false
}

func (t TemplateExt) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

func (t *TemplateExt) UnmarshalJSON(data []byte) error {
	var s string

	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	e, err := Parse(s)

	if err != nil {
		return err
	}

	*t = e

	return nil
}
