//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Any change will be overwritten                                                   *
//* Generated by github.com/boundedinfinity/enumer                                   *
//*                                                                                  *
//************************************************************************************

package schema_ext

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

type SchemaExt string
type SchemaExts []SchemaExt

func Slice(es ...SchemaExt) SchemaExts {
	var s SchemaExts

	for _, e := range es {
		s = append(s, e)
	}

	return s
}

const (
	Json SchemaExt = "json"
	Yaml SchemaExt = "yaml"
	Yml  SchemaExt = "yml"
)

var (
	All = SchemaExts{
		Json,
		Yaml,
		Yml,
	}
)

func Is(v string) bool {
	return All.Is(v)
}

func Parse(v string) (SchemaExt, error) {
	return All.Parse(v)
}

func Strings() []string {
	return All.Strings()
}

func (t SchemaExt) String() string {
	return string(t)
}

var ErrSchemaExtInvalid = errors.New("invalid enumeration type")

func Error(vs SchemaExts, v string) error {
	return fmt.Errorf(
		"%w '%v', must be one of %v",
		ErrSchemaExtInvalid, v, strings.Join(vs.Strings(), ","),
	)
}

func (t SchemaExts) Strings() []string {
	var ss []string

	for _, v := range t {
		ss = append(ss, v.String())
	}

	return ss
}

func (t SchemaExts) Parse(v string) (SchemaExt, error) {
	var o SchemaExt
	var f bool
	n := strings.ToLower(v)

	for _, e := range t {
		if strings.ToLower(e.String()) == n {
			o = e
			f = true
			break
		}
	}

	if !f {
		return o, Error(t, v)
	}

	return o, nil
}

func (t SchemaExts) Is(v string) bool {
	var f bool

	for _, e := range t {
		if string(e) == v {
			f = true
			break
		}
	}

	return f
}

func (t SchemaExts) Contains(v SchemaExt) bool {
	for _, e := range t {
		if e == v {
			return true
		}
	}

	return false
}

func (t SchemaExt) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

func (t *SchemaExt) UnmarshalJSON(data []byte) error {
	var s string

	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	e, err := Parse(s)

	if err != nil {
		return err
	}

	*t = e

	return nil
}
